server:
  port: 8765

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

#spring:
#  application.name: api-gateway
#  cloud:
#    gateway:
#      discovery.locator.enabled: true
#      routes:
#        - id: shipping-service-id
#          uri: lb://SHIPPING-SERVICE
#          predicates:
#            Path=/api/shipping/**
#          filters:
#            - AuthFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka